### PR TITLE
Support for custom data properties

### PR DESCRIPTION
**Pull request by willmcclellan**
We have a use-case for assigning custom properties to SVGs based off GeoJSON properties. I've quickly pulled together this which might need some tweaking and happy to take some feedback. Couple of points up for discussion:

1. I chose `properties.data` of geojson feature as a namespace for any custom props. That key name might need to be more explicit (maybe `customData`)
2. I didn't include any validation for SVG foreign namespace spec https://www.w3.org/TR/SVG/extend.html#ForeignNamespaces. Is it ok to put that responsibility on the user?

### CODE REVIEW

**Comment by maphew** [comment]
> if attributes option given as json (existing behavior), each of the
key:value of json would be attached to every svg element.

Speaking as lurker, I've not use geojson2svg in a real way yet, but my most
likely scenario would have different attributes for different elements.

Ex: polygon A has attributes ID=06 and Species=Wolf while poly B has ID=10
and Species=Moose.

Forgive the intrusion if this is offtopic.

**Comment by gagan-bansal** [comment]
Yes use case of 
>  if attributes option given as json (existing behavior), each of the key:value of json would be attached to every svg element.

are very less.

Your change now seems basic requirement. 
Lets discuss a little more about my suggestion
```
"attributes": [ "properties.foo", "properties.bar"]
```
This way we are not forcing user to modify geojson to our requirement.

**Comment by willmcclellan** [comment]
That sounds pretty good. I was thinking it's a little more restrictive in that it's dependant on having consistent attributes you want to apply to every element, but we could get around that by just listing out keys in attributes and ignoring if it doesn't exist in each feature properties.

I'll push an update tomorrow for review 😃

**Comment by gagan-bansal** [comment]
Seems nice, great! You can proceed.
Thanks for the pull request.

**Comment by allochi** [comment]
Hi,

This is create, this is exactly what I need in my current project, any chance this feature get merged soon?

Thanks for both of you.

**Comment by gagan-bansal** [comment]
@willmcclellan, I'll update today as per our discussion.
@allochi

**Comment by allochi** [comment]
Thanks a lot, meanwhile I'm using @willmcclellan source, and it works nicely!

Again, thanks for both of you! this just comes in the right time for me :)

**Comment by willmcclellan** [comment]
Sorry I got side-tracked with some other work. If you're happy to pick it up @gagan-bansal that would be awesome as not sure when I'll get back round to it :)

**Comment by gagan-bansal** [comment]
@willmcclellan No issue I am working on it.

**Comment by gagan-bansal** [comment]
Commit 77f4365 adds this feature. Option `attributes` can be given like: 
```"attributes": [ "properties.foo", "properties.bar"]```

**Pull request closed without merging**
